/// Flutter icons Arutalav2icon
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Arutalav2icon
///      fonts:
///       - asset: fonts/Arutalav2icon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Arutalav2icon {
  Arutalav2icon._();

  static const _kFontFam = 'Arutalav2icon';
  static const String? _kFontPkg = null;

  static const IconData book_type_1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_type = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_user_round_1 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData house_1 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData house = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_user_round = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData terjemah_1 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData terjemah = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
